In [1]:
import os
import pickle

from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from run_multilabel_classifier import _load_comments, run

In [2]:
train_comments_path = os.path.join('../../../', 'data/train.csv')
test_comments_path = os.path.join('../../../', 'data/test_clean.csv')

## Logistic regression

In [3]:
param_grid = [{
        'estimator__bag_of_words__stop_words': ['english'],
        'estimator__bag_of_words__ngram_range': [(1, 2)],
        'estimator__bag_of_words__max_features': [500],
        'estimator__dim_reduct__n_components': [300],
        'estimator__normalizer__norm': ['l2'],
        'estimator__classifier__C': [10., 100.]
}]


clf = LogisticRegression()

#### Train phase

In [4]:
multilabel_clf = run(param_grid, clf, comments_file=train_comments_path)

0 15294
1 1595
2 8449
3 478
4 7877
5 1405
0 5849
[15294  1595  8449   478  7877  1405]
0 9445
1 4254
2 8449
3 5371
4 7877
5 4444
143346
39840
Fitting 5 folds for each of 2 candidates, totalling 10 fits


/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 3 is present in all training examples.
  str(classes[c]))
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/

{'mean_fit_time': array([0.1208416 , 0.11325073]),
 'mean_score_time': array([0.00968542, 0.01019158]),
 'mean_test_score': array([0.54285714, 0.51428571]),
 'mean_train_score': array([0.95357143, 1.        ]),
 'param_estimator__bag_of_words__max_features': masked_array(data=[500, 500],
             mask=[False, False],
       fill_value='?',
            dtype=object),
 'param_estimator__bag_of_words__ngram_range': masked_array(data=[(1, 2), (1, 2)],
             mask=[False, False],
       fill_value='?',
            dtype=object),
 'param_estimator__bag_of_words__stop_words': masked_array(data=['english', 'english'],
             mask=[False, False],
       fill_value='?',
            dtype=object),
 'param_estimator__classifier__C': masked_array(data=[10.0, 100.0],
             mask=[False, False],
       fill_value='?',
            dtype=object),
 'param_estimator__dim_reduct__n_components': masked_array(data=[300, 300],
             mask=[False, False],
       fill_value='?',
   

/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


#### Saving the model

In [5]:
with open('./saved_models/logreg_trained_mlutils.pkl', 'wb') as saved_model:
    pickle.dump(multilabel_clf, file=saved_model)

#### Loading the model and testing it

In [6]:
with open('./saved_models/logreg_trained_mlutils.pkl', 'rb') as saved_model:
    loaded_clf = pickle.load(saved_model)
    print(loaded_clf)
    X_test, y_test = _load_comments(test_comments_path)
    y_test_predict = loaded_clf.predict(X_test)

    print(classification_report(y_test, y_test_predict))

OneVsRestClassifier(estimator=Pipeline(memory=None,
     steps=[('bag_of_words', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=500, min_df=1,
        ngram_range=(1, 2), norm='l2', preprocessor=None, smooth_idf=T...ty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))]),
          n_jobs=1)
0 6090
1 367
2 3691
3 211
4 3427
5 712
0 2416
[6090  367 3691  211 3427  712]
0 3674
1 2049
2 1275
3 2205
4 3427
5 1704
57735
14334
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       100
          1       0.00      0.00      0.00        11
          2       0.78      0.55      0.65        56
          3       0.00      0.00      0.00         8
          4       0.73      0.46      0.56        48
          5       0.00      0.00      0.00        13

avg / total 

/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## Naive bayes

In [7]:
param_grid = [{
        'estimator__bag_of_words__stop_words': ['english'],
        'estimator__bag_of_words__ngram_range': [(1, 2)],
        'estimator__bag_of_words__max_features': [500],
        'estimator__dim_reduct__n_components': [300],
        'estimator__normalizer__norm': ['l2'],
        'estimator__classifier__alpha': [1.0],
        'estimator__classifier__binarize': [0.0]
}]

#### Train phase

In [8]:
multilabel_clf = run(param_grid, BernoulliNB(), comments_file=train_comments_path)

0 15294
1 1595
2 8449
3 478
4 7877
5 1405
0 5849
[15294  1595  8449   478  7877  1405]
0 9445
1 4254
2 8449
3 5371
4 7877
5 4444
143346
39840
Fitting 5 folds for each of 1 candidates, totalling 5 fits


/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 3 is present in all training examples.
  str(classes[c]))
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/

{'mean_fit_time': array([0.11363225]),
 'mean_score_time': array([0.0103054]),
 'mean_test_score': array([0.42857143]),
 'mean_train_score': array([0.72857143]),
 'param_estimator__bag_of_words__max_features': masked_array(data=[500],
             mask=[False],
       fill_value='?',
            dtype=object),
 'param_estimator__bag_of_words__ngram_range': masked_array(data=[(1, 2)],
             mask=[False],
       fill_value='?',
            dtype=object),
 'param_estimator__bag_of_words__stop_words': masked_array(data=['english'],
             mask=[False],
       fill_value='?',
            dtype=object),
 'param_estimator__classifier__alpha': masked_array(data=[1.0],
             mask=[False],
       fill_value='?',
            dtype=object),
 'param_estimator__classifier__binarize': masked_array(data=[0.0],
             mask=[False],
       fill_value='?',
            dtype=object),
 'param_estimator__dim_reduct__n_components': masked_array(data=[300],
             mask=[False],

/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


#### Saving the model

In [9]:
with open('./saved_models/naiveB_multilabel.pkl', 'wb') as saved_model:
	pickle.dump(multilabel_clf, file=saved_model)

#### Loading the model and testing it

In [10]:
with open('./saved_models/naiveB_multilabel.pkl', 'rb') as saved_model:
    loaded_clf = pickle.load(saved_model)
    print(loaded_clf)
    X_test, y_test = _load_comments(test_comments_path)
    y_test_predict = loaded_clf.predict(X_test)

    print(classification_report(y_test, y_test_predict))

OneVsRestClassifier(estimator=Pipeline(memory=None,
     steps=[('bag_of_words', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=500, min_df=1,
        ngram_range=(1, 2), norm='l2', preprocessor=None, smooth_idf=T...norm='l2')), ('classifier', BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True))]),
          n_jobs=1)
0 6090
1 367
2 3691
3 211
4 3427
5 712
0 2416
[6090  367 3691  211 3427  712]
0 3674
1 2049
2 1275
3 2205
4 3427
5 1704
57735
14334
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       100
          1       0.20      0.25      0.22         4
          2       0.74      0.37      0.49        63
          3       0.00      0.00      0.00         3
          4       0.53      0.33      0.41        51
          5       0.00      0.00      0.00         8

avg / total 

/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## Decision tree

In [11]:
param_grid = [{
        'estimator__bag_of_words__stop_words': ['english'],
        'estimator__bag_of_words__ngram_range': [(1, 2)],
        'estimator__bag_of_words__max_features': [500],
        'estimator__dim_reduct__n_components': [300],
        'estimator__normalizer__norm': ['l2'],
        'estimator__classifier__max_depth': [5, 10, 15]
}]

#### Train phase

In [12]:
multilabel_clf = run(param_grid, DecisionTreeClassifier(), comments_file=train_comments_path)

0 15294
1 1595
2 8449
3 478
4 7877
5 1405
0 5849
[15294  1595  8449   478  7877  1405]
0 9445
1 4254
2 8449
3 5371
4 7877
5 4444
143346
39840
Fitting 5 folds for each of 3 candidates, totalling 15 fits


/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label not 3 is present in all training examples.
  str(classes[c]))
/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/multiclass.py:76: UserWarning: Label 0 is present in all training examples.
  str(classes[c]))
/

{'mean_fit_time': array([0.12937493, 0.12560506, 0.13066373]),
 'mean_score_time': array([0.01072836, 0.0102448 , 0.00955062]),
 'mean_test_score': array([0.21428571, 0.22857143, 0.2       ]),
 'mean_train_score': array([0.99642857, 0.99642857, 0.99642857]),
 'param_estimator__bag_of_words__max_features': masked_array(data=[500, 500, 500],
             mask=[False, False, False],
       fill_value='?',
            dtype=object),
 'param_estimator__bag_of_words__ngram_range': masked_array(data=[(1, 2), (1, 2), (1, 2)],
             mask=[False, False, False],
       fill_value='?',
            dtype=object),
 'param_estimator__bag_of_words__stop_words': masked_array(data=['english', 'english', 'english'],
             mask=[False, False, False],
       fill_value='?',
            dtype=object),
 'param_estimator__classifier__max_depth': masked_array(data=[5, 10, 15],
             mask=[False, False, False],
       fill_value='?',
            dtype=object),
 'param_estimator__dim_reduct_

/home/zvonimir/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


#### Saving the model

In [13]:
with open('./saved_models/dec_tree_multilabel.pkl', 'wb') as saved_model:
	pickle.dump(multilabel_clf, file=saved_model)

#### Loading the model and testing it

In [14]:
with open('./saved_models/dec_tree_multilabel.pkl', 'rb') as saved_model:
    loaded_clf = pickle.load(saved_model)
    print(loaded_clf)
    X_test, y_test = _load_comments(test_comments_path)
    y_test_predict = loaded_clf.predict(X_test)

    print(classification_report(y_test, y_test_predict))

OneVsRestClassifier(estimator=Pipeline(memory=None,
     steps=[('bag_of_words', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=500, min_df=1,
        ngram_range=(1, 2), norm='l2', preprocessor=None, smooth_idf=T...      min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'))]),
          n_jobs=1)
0 6090
1 367
2 3691
3 211
4 3427
5 712
0 2416
[6090  367 3691  211 3427  712]
0 3674
1 2049
2 1275
3 2205
4 3427
5 1704
57735
14334
             precision    recall  f1-score   support

          0       1.00      1.00      1.00       100
          1       0.00      0.00      0.00         5
          2       0.66      0.54      0.60        68
          3       0.00      0.00      0.00         3
          4       0.71      0.62      0.66        63
          5       0.11      0.10      0.11        10

avg / total 